CLOUDP-73696: Implement backup configuration ops manager go client
mongodb/go-client-mongodb-ops-manager pull request #55
Opened 2020-09-28 07:14 UTC by andreaangiolillo

## Proposed changes

_Jira ticket:_ CLOUDP-73696

Closes #[issue number]

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments

2020-09-28 09:04 UTC, andreaangiolillo commented
@gssbzn tagging you here so that you can review this PR once you're back

2020-09-29 08:18 UTC, gssbzn requested changes
Just a couple of small things, good work

2020-09-29 08:18 UTC, gssbzn commented on opsmngr/backup_configs.go
> +	SSLEnabled         bool     `json:"sslEnabled,omitempty"`
`omitempty` and bool should use a pointer on the bool or `false` won't be serialised

2020-09-29 08:18 UTC, gssbzn commented on opsmngr/backup_configs.go
> +// BackupConfigs represents an array of BackupConfig
```suggestion
// BackupConfigs represents a paginated collection of BackupConfig
```

2020-09-29 08:18 UTC, gssbzn commented on opsmngr/backup_configs_test.go
> +func TestAutomation_GetBackupConfig(t *testing.T) {
[copy/paste] should this be 
```suggestion
func TestBackupConfigsServiceOp_Get(t *testing.T) {
```

2020-09-29 08:18 UTC, gssbzn commented on opsmngr/backup_configs_test.go
> +func TestAutomation_ListBackupConfig(t *testing.T) {
same as above, the test method name should match the Struct, underscore, function pattern

2020-09-29 09:24 UTC, gssbzn approved these changes
LGTM

2020-09-29 09:24 UTC, merged